/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student;
import java.util.*;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import Connection.Conn;
import java.util.regex.*;
import java.sql.*;
import java.text.SimpleDateFormat;


/**
 *
 * @author piyush-garg
 */
public class studentRegistrationUI extends javax.swing.JFrame {

    private final int securitykey = 5821;
    
    public studentRegistrationUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        standardfield = new java.awt.TextField();
        label4 = new java.awt.Label();
        fathersnamefield = new java.awt.TextField();
        mothersnamefield = new java.awt.TextField();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        parentsmobilenofield = new java.awt.TextField();
        label8 = new java.awt.Label();
        statefield = new java.awt.TextField();
        label9 = new java.awt.Label();
        pincodefield = new java.awt.TextField();
        studentemailidfield = new java.awt.TextField();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        passwordfield = new javax.swing.JPasswordField();
        confirmpassword = new javax.swing.JPasswordField();
        label13 = new java.awt.Label();
        gendermale = new javax.swing.JRadioButton();
        genderfemale = new javax.swing.JRadioButton();
        label15 = new java.awt.Label();
        countryfield = new java.awt.TextField();
        registerstudent = new javax.swing.JButton();
        dateofbirthfield = new com.toedter.calendar.JDateChooser();
        studentnamefield = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management System");
        setName("dateofbirthfield"); // NOI18N

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        label1.setText("REGISTER STUDENT DETAILS");

        label2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label2.setText("Student's Name : ");

        label3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label3.setText("Standard : ");

        standardfield.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        standardfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardfieldActionPerformed(evt);
            }
        });

        label4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label4.setText("Father's Name : ");

        fathersnamefield.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        fathersnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathersnamefieldActionPerformed(evt);
            }
        });

        mothersnamefield.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mothersnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mothersnamefieldActionPerformed(evt);
            }
        });

        label5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label5.setText("Mother's Name : ");

        label6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label6.setText("Date of Birth : ");

        label7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label7.setText("Parent's Mobile No. : ");

        parentsmobilenofield.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        parentsmobilenofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentsmobilenofieldActionPerformed(evt);
            }
        });

        label8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label8.setText("State : ");

        statefield.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        statefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statefieldActionPerformed(evt);
            }
        });

        label9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label9.setText("Pincode : ");

        pincodefield.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pincodefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pincodefieldActionPerformed(evt);
            }
        });

        studentemailidfield.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        studentemailidfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentemailidfieldActionPerformed(evt);
            }
        });

        label10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label10.setText("Student's Email ID : ");

        label11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label11.setText("Password : ");

        label12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label12.setText("Confirm Password : ");

        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });

        confirmpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpasswordActionPerformed(evt);
            }
        });

        label13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label13.setText("Gender : ");

        gendermale.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gendermale.setText("Male");
        gendermale.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gendermale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gendermaleActionPerformed(evt);
            }
        });

        genderfemale.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        genderfemale.setText("Female");
        genderfemale.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        label15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label15.setText("Country : ");

        countryfield.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        countryfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryfieldActionPerformed(evt);
            }
        });

        registerstudent.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        registerstudent.setText("Register");
        registerstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerstudentActionPerformed(evt);
            }
        });

        dateofbirthfield.setDateFormatString("yyyy-MM-dd");
        dateofbirthfield.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        dateofbirthfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        studentnamefield.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        studentnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentnamefieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pincodefield, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mothersnamefield, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                                    .addComponent(fathersnamefield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(standardfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(parentsmobilenofield, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(countryfield, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statefield, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentemailidfield, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(registerstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateofbirthfield, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentnamefield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gendermale)
                                .addGap(108, 108, 108)
                                .addComponent(genderfemale)
                                .addGap(93, 93, 93))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(standardfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fathersnamefield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mothersnamefield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateofbirthfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(parentsmobilenofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countryfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pincodefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentemailidfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gendermale)
                        .addComponent(genderfemale)))
                .addGap(42, 42, 42)
                .addComponent(registerstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );

        label5.getAccessibleContext().setAccessibleName("Mother's Name");
        label7.getAccessibleContext().setAccessibleName("Country : ");

        getAccessibleContext().setAccessibleName("Student Registration form");
        getAccessibleContext().setAccessibleDescription("");

        setBounds(0, 0, 872, 956);
    }// </editor-fold>//GEN-END:initComponents

    public boolean isNumeric(String str){
        try{
            Double.parseDouble(str);
            return true;
        }
        catch(NumberFormatException e){
            return false;
        }
    }
    public boolean isString(String str){
        try{
            Double.parseDouble(str);
            return false;
        }
        catch(NumberFormatException e){
            return true;
        }
    }
    
    private void parentsmobilenofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentsmobilenofieldActionPerformed
        // TODO add your handling code here:
        
        if(parentsmobilenofield.getText().length() < 10 || parentsmobilenofield.getText().length() > 10 || !isNumeric(parentsmobilenofield.getText())){
            JOptionPane.showMessageDialog(this,"Please Enter a Valid Phone Number.");
        }
        
    }//GEN-LAST:event_parentsmobilenofieldActionPerformed

    private void statefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statefieldActionPerformed
        // TODO add your handling code here:
        if(statefield.getText().equals("") || isNumeric(statefield.getText())){
            JOptionPane.showMessageDialog(this,"Please Enter a Valid State name.");
        }
        
    }//GEN-LAST:event_statefieldActionPerformed

    private void pincodefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pincodefieldActionPerformed
        // TODO add your handling code here:
        if(pincodefield.getText().toString().length() > 6 || isString(pincodefield.getText())){
            JOptionPane.showMessageDialog(this,"Please Enter a Valid Pincode.");
        }
        
    }//GEN-LAST:event_pincodefieldActionPerformed

    private void studentemailidfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentemailidfieldActionPerformed
        // TODO add your handling code here:
        String regex = "^[A-Za-z0-9+_.-]+@(.+)$";  
        Pattern pattern = Pattern.compile(regex); 
        Matcher matcher = pattern.matcher(studentemailidfield.getText());
        if(!matcher.matches()){
            JOptionPane.showMessageDialog(this,"Please Enter a Valid Email ID.");
            setVisible(true);
        }
    }//GEN-LAST:event_studentemailidfieldActionPerformed

    private void countryfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryfieldActionPerformed
        // TODO add your handling code here:
        if(countryfield.getText().equals("") || isNumeric(countryfield.getText())){
            JOptionPane.showMessageDialog(this,"Please Enter a Valid Country name.");
        }
    }//GEN-LAST:event_countryfieldActionPerformed

    private void registerstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerstudentActionPerformed
        // TODO add your handling code here:
        
        String name = studentnamefield.getText().toUpperCase();
        int rollno = (int)(Math.random()*(9999-1+1)+1);
        String standard = standardfield.getText().toUpperCase();
        String fathersname = fathersnamefield.getText().toUpperCase();
        String mothersname = mothersnamefield.getText().toUpperCase();
        SimpleDateFormat simpledate = new SimpleDateFormat("yyyy-MM-dd");
        
//        String dob = simpledate.format(dateofbirthfield.getDate());
        String dob = simpledate.format(dateofbirthfield.getDate());
        long parentsnumber = Long.parseLong(parentsmobilenofield.getText());
        String country = countryfield.getText().toUpperCase();
        String state = statefield.getText().toUpperCase();
        int pincode = Integer.parseInt(pincodefield.getText());
        String student_email = studentemailidfield.getText().toUpperCase();
        String password = new String(passwordfield.getPassword());
        password += securitykey;
        int marks = 0;
        int percentage = 0;
        char grade = ' ';
        char gender = ' ';
        
        if(gendermale.isSelected()) gender = 'M';
        else if(genderfemale.isSelected()) gender = 'F';
        System.out.println(dob);
        try {
            String query = "insert into students values('"+rollno+"', '"+name+"', '"+standard+"', '"+fathersname+"', '"+mothersname+"', '"+dob+"', '"+country+"', '"+state+"', '"+pincode+"', '"+student_email+"', '"+password+"', '"+marks+"','"+percentage+"','"+grade+"','"+gender+"','"+parentsnumber+"')";            Conn conn = new Conn();            
            int response = conn.s.executeUpdate(query);
            System.out.println(response);
            StudentloginUI login = new StudentloginUI();
            login.setVisible(true);
            JOptionPane.showMessageDialog(this,"Student Registered successfully.");
            JOptionPane.showMessageDialog(this,"Your Roll No. : "+rollno);
            setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_registerstudentActionPerformed

    private void mothersnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mothersnamefieldActionPerformed
        // TODO add your handling code here:
        if(mothersnamefield.getText().equals("") || isNumeric(mothersnamefield.getText())){
            JOptionPane.showMessageDialog(this,"Please Enter a Valid Mother Name.");
        }
        
    }//GEN-LAST:event_mothersnamefieldActionPerformed

    private void gendermaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gendermaleActionPerformed
        // TODO add your handling code here:
        f=new JFrame();  
        group = new ButtonGroup();
        group.add(genderfemale);
        group.add(gendermale);
    }//GEN-LAST:event_gendermaleActionPerformed

    private void confirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpasswordActionPerformed
        // TODO add your handling code here:
        if(passwordfield.getPassword() != confirmpassword.getPassword()){
            JOptionPane.showMessageDialog(null,"Confirm Password is not same as Entered password.");
        }
    }//GEN-LAST:event_confirmpasswordActionPerformed

    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfieldActionPerformed

    private void fathersnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathersnamefieldActionPerformed
        // TODO add your handling code here:
        if(fathersnamefield.getText().equals("") || isNumeric(fathersnamefield.getText())){
            JOptionPane.showMessageDialog(this,"Please Enter a Valid Father Name.");
        }
    }//GEN-LAST:event_fathersnamefieldActionPerformed

    private void standardfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardfieldActionPerformed
        // TODO add your handling code here:
        if(standardfield.getText().equals("") || isNumeric(standardfield.getText())){
            JOptionPane.showMessageDialog(this,"Please Enter a Valid Standard.");
        }
    }//GEN-LAST:event_standardfieldActionPerformed

    private void studentnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentnamefieldActionPerformed
        // TODO add your handling code here:
        if(studentnamefield.getText().equals("") || isNumeric(studentnamefield.getText())){
            JOptionPane.showMessageDialog(this,"Please Enter a Valid Student Name.");
        }
    }//GEN-LAST:event_studentnamefieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentRegistrationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentRegistrationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentRegistrationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentRegistrationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
           
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentRegistrationUI().setVisible(true);
            }
        });
    }   
    static ArrayList<String> record = new ArrayList<>();
    
    ButtonGroup group;
    JFrame f; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmpassword;
    private java.awt.TextField countryfield;
    private com.toedter.calendar.JDateChooser dateofbirthfield;
    private java.awt.TextField fathersnamefield;
    private javax.swing.JRadioButton genderfemale;
    private javax.swing.JRadioButton gendermale;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label15;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.TextField mothersnamefield;
    private java.awt.TextField parentsmobilenofield;
    private javax.swing.JPasswordField passwordfield;
    private java.awt.TextField pincodefield;
    private javax.swing.JButton registerstudent;
    private java.awt.TextField standardfield;
    private java.awt.TextField statefield;
    private java.awt.TextField studentemailidfield;
    private java.awt.TextField studentnamefield;
    // End of variables declaration//GEN-END:variables
}
